##
# Example: ansible-playbook -i inventory vault-playbook.yml -k -K --ask-vault-pass
##

---
- name: Learning Ansible Vault
  hosts: myinstance
  become: true

  vars_files:
    - vars/vault-vars.yml

  tasks:
    - name: Generate password hash sha512
      ansible.builtin.set_fact:
        new_hash_pass: "{{ new_user_pass | password_hash('sha512', new_user_secret ) }}"

    - name: Create user
      ansible.builtin.user:
        name: "{{ new_user_name }}"
        password: "{{ new_hash_pass }}"
