##
# Example: ansible-playbook -i inventory tools-playbook.yml -k -K
##

---
- name: Learning Ansible Conditionals, Loops, and Handlers
  hosts: myinstance
  become: true

  vars:
    - packages:
        - lighttpd
        - fzf
    - more_packages:
        - ncdu
        - fd-find

  tasks:
    - name: Install Packages
      ansible.builtin.package:
        name: "{{ packages }}"
        state: present
      register: operation
      notify: Start lighttpd

    - name: Restart service lighttpd
      ansible.builtin.service:
        name: lighttpd
        state: restarted
      when: operation is not changed

    - name: Install More Packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop: "{{ more_packages }}"

  handlers:
    - name: Start lighttpd
      ansible.builtin.service:
        name: lighttpd
        state: started
        enabled: true
      when: operation is changed
