##
# Example: ansible-playbook -i inventory lookup-playbook.yml -k -K
##

---
- name: Learning Ansible Lookups
  hosts: myinstance
  become: true


  vars:
    test_dict: "{{lookup('file', 'dictionaryyyy.json', errors='warn')}}"
    dict_content: "{{lookup('file', 'dictionary.json', errors='warn') | from_json }}"

  tasks:
    - name: Reading var
      ansible.builtin.debug:
        var: test_dict

    - name: Reading var
      ansible.builtin.debug:
        var: dict_content
