##
# Example: ansible-playbook -i inventory variables-playbook.yml -k -K
##

---
- name: Testing variables
  hosts: myinstance
  become: true

  tasks:
    - name: Print test_string variable
      ansible.builtin.debug:
        var: test_string
    - name: Print test_array variable
      ansible.builtin.debug:
        var: test_array
    - name: Print test_dic variable
      ansible.builtin.debug:
        var: test_dic
    - name: Print the list of sources used as inventory
      ansible.builtin.debug:
        var: ansible_inventory_sources
    - name: Print the connection plugin actually used for the task on the target host
      ansible.builtin.debug:
        var: ansible_connection
    - name: Print Ansible facts
      ansible.builtin.debug:
        var: ansible_facts
