---
- name: Use cases?
  hosts: myinstance
  become: true

  tasks:
    - name: Create custom fact directory
      ansible.builtin.file:
        path: "/etc/ansible/facts.d"
        state: directory
        owner: root
        group: root
        mode: '0644'

    # Why might we want to create a custom facts file on each host?
    - name: Creating facts file
      community.general.ini_file:
        path: /etc/ansible/facts.d/custom.fact
        section: haproxy
        option: haproxy_ip
        value: 192.168.123.123
        mode: '0644'

    # Decipher how this variable works, in releation to the custom fact above.
    - name: Print haproxy_ip
      ansible.builtin.debug:
        var: ansible_local.custom.haproxy.haproxy_ip

    # Why might we set a fact in the middle of a task like this instead of including it in a var file?
    - name: Create a new variable with date
      ansible.builtin.set_fact:
        live_variable: "{{ ansible_date_time }}"

    - name: Print life_variable
      ansible.builtin.debug:
        var: live_variable
