##
# Example: ansible-playbook -i inventory filters-playbook.yml -k
##

---
- name: Using Ansible Filters
  hosts: myinstance

  vars:
    ip_array:
      - "192.168.1.1"
      - "192.16.2,2"
      - "192.168.23.32"
      - false
    url: http://user:password@www.acme.com:9000/dir/index.html?query=term#fragment

  tasks:
    - name: Obtain file content
      ansible.builtin.slurp:
        file: ./dictionary.json
      register: jsondict

    - name: Parse json to an ansible dictionary
      ansible.builtin.set_fact:
        mydict: "{{ jsondict.stdout | from_json }}"

    - name: Display all cluster names
      ansible.builtin.debug:
        var: item
      loop: "{{ mydict.domain_definition | json_query('domain.cluster[*].name') }}"

    - name: Display all server names
      ansible.builtin.debug:
        var: item
      loop: "{{ mydict.domain_definition | json_query('domain.server[*].name') }}"

    - name: Display all dictionary names
      ansible.builtin.debug:
        var: item
      loop: "{{ mydict.domain_definition | json_query('domain.library[*].name') }}"

    - name: Test ip_array IPs
      ansible.builtin.debug:
        var: item | ipv4
      loop: "{{ ip_array }}"
      failed_when: item | ipv4 == false
      ignore_errors: true

    - name: Parse url in multiple pieces
      ansible.builtin.set_fact:
        urlparsed: "{{ url | urlsplit }}"

    - name: "Display URL properties"
      ansible.builtin.debug:
        msg: "Hostname: {{ urlparsed.hostname }} / Port: {{ urlparsed.port }} / Path: {{ urlparsed.path }}"
